"use client";

import Link from "next/link";
import { Appointment } from "../types/appointment.types";
import { formatAppointmentDate, formatAppointmentTime, visitTypeLabel } from "../utils/appointment-format";
import { AppointmentStatusChip } from "./appointment-status-chip";

export function AppointmentTable({ items }: { items: Appointment[] }) {
  if (!items.length) return <section className="rounded-lg border border-outline-variant bg-surface-container-lowest p-6"><p className="text-sm font-bold text-on-surface">No appointments found.</p><p className="mt-1 text-xs text-on-surface-variant">Try changing filters or create a new appointment.</p></section>;
  return <section className="overflow-hidden rounded-lg border border-outline-variant bg-surface-container-lowest"><div className="max-h-[58vh] overflow-auto"><table className="w-full min-w-[900px] border-collapse text-left text-xs"><thead className="sticky top-0 z-10 bg-surface-container-low"><tr className="border-b border-outline-variant text-[10px] uppercase tracking-wider text-on-surface-variant"><th className="px-3 py-2">Appointment</th><th className="px-3 py-2">Patient</th><th className="px-3 py-2">Doctor</th><th className="px-3 py-2">Date</th><th className="px-3 py-2">Time</th><th className="px-3 py-2">Visit type</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Actions</th></tr></thead><tbody className="divide-y divide-outline-variant">{items.map((appointment) => <tr key={appointment.uuid} className="hover:bg-surface"><td className="px-3 py-2 font-mono text-[11px] font-bold text-on-surface">{appointment.appointmentNumber}</td><td className="px-3 py-2"><p className="font-semibold text-on-surface">{appointment.patientName || "—"}</p><p className="font-mono text-[10px] text-on-surface-variant">{appointment.patientMrn || "—"}</p></td><td className="px-3 py-2"><p className="font-semibold text-on-surface">{appointment.doctorName || "—"}</p><p className="font-mono text-[10px] text-on-surface-variant">{appointment.doctorCode || "—"}</p></td><td className="px-3 py-2 text-on-surface-variant">{formatAppointmentDate(appointment.appointmentDate)}</td><td className="px-3 py-2 text-on-surface-variant">{formatAppointmentTime(appointment.startTime)} – {formatAppointmentTime(appointment.endTime)}</td><td className="px-3 py-2 text-on-surface-variant">{visitTypeLabel[appointment.visitType]}</td><td className="px-3 py-2"><AppointmentStatusChip status={appointment.status} /></td><td className="px-3 py-2"><Link href={`/appointments/${appointment.uuid}`} className="rounded border border-outline-variant px-2 py-1 text-[10px] font-bold text-primary hover:bg-primary/5">View</Link></td></tr>)}</tbody></table></div></section>;
}
