"use client";

import { useState } from "react";
import { AlertDialog, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useAvailableSlots, useRescheduleAppointment } from "../hooks/use-appointments";
import { Appointment } from "../types/appointment.types";
import { formatAppointmentTime } from "../utils/appointment-format";

export function RescheduleDialog({ appointment, open, onClose }: { appointment: Appointment; open: boolean; onClose: () => void }) {
  const [date, setDate] = useState(appointment.appointmentDate); const [startTime, setStartTime] = useState(""); const [endTime, setEndTime] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState("");
  const slots = useAvailableSlots(open ? appointment.doctorUuid : undefined, open ? date : undefined); const reschedule = useRescheduleAppointment();
  const submit = async () => { if (!startTime || !endTime) { setError("Select an available time slot."); return; } try { await reschedule.mutateAsync({ uuid: appointment.uuid, startTime: `${date}T${startTime}`, endTime: `${date}T${endTime}`, reason: reason || undefined }); onClose(); } catch (caught: any) { setError(caught?.response?.status === 409 ? "This slot is no longer available. Select another slot." : "Unable to reschedule this appointment."); } };
  return <AlertDialog open={open}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reschedule appointment</AlertDialogTitle><AlertDialogDescription>Select a new date and a server-provided available slot.</AlertDialogDescription></AlertDialogHeader><label className="mt-3 block text-xs font-semibold">New date<input type="date" value={date} onChange={(event) => { setDate(event.target.value); setStartTime(""); }} className="mt-1 block h-9 rounded border border-outline-variant bg-surface px-2" /></label><div className="mt-3"><p className="text-xs font-semibold">Available slots</p>{slots.isLoading ? <p className="mt-1 text-xs text-on-surface-variant">Loading slots…</p> : <div className="mt-2 flex flex-wrap gap-2">{slots.data?.slots.map((slot) => <button type="button" key={`${slot.startTime}-${slot.endTime}`} disabled={!slot.available} onClick={() => { setStartTime(slot.startTime); setEndTime(slot.endTime); }} className={`rounded border px-2 py-1 text-xs ${slot.available ? startTime === slot.startTime ? "border-primary bg-primary text-on-primary" : "border-outline-variant" : "cursor-not-allowed text-outline line-through"}`}>{formatAppointmentTime(slot.startTime)}</button>)}</div>}</div><label className="mt-3 block text-xs font-semibold">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 block w-full rounded border border-outline-variant bg-surface p-2" rows={3} /></label>{error && <p role="alert" className="mt-2 text-xs text-error">{error}</p>}<AlertDialogFooter><button onClick={onClose} className="h-8 rounded-md border border-outline-variant px-3 text-xs font-semibold">Close</button><button disabled={reschedule.isPending || !startTime} onClick={submit} className="h-8 rounded-md bg-primary px-3 text-xs font-bold text-on-primary disabled:opacity-50">{reschedule.isPending ? "Saving…" : "Confirm Reschedule"}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>;
}
